# Model arguments
model_name_or_path: deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: DigitalLearningGmbH/MATH-lighteval
dataset_configs:
- train
# Num processes is less by 1 as vLLM is using 1 GPU
num_processes: 3 # 3 = 4 - 1 (total gpu - vllm GPU)

# GRPO trainer config
bf16: true
use_vllm: true
vllm_device: auto
vllm_gpu_memory_utilization: 0.7
do_eval: true
eval_strategy: steps
eval_steps: 10
gradient_accumulation_steps: 8
gradient_clipping: 1.0
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 3.0e-06
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine
max_prompt_length: 512
max_completion_length: 1024
max_steps: -1
num_generations: 7
num_train_epochs: 1
output_dir: data/Test
overwrite_output_dir: true
per_device_eval_batch_size: 4   
per_device_train_batch_size: 4
push_to_hub: false
save_strategy: "no"
seed: 42
warmup_ratio: 0.1
